name: buf

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
    - uses: bufbuild/buf-lint-action@v1

  breaking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
    - uses: bufbuild/buf-breaking-action@v1
      with:
        against: https://github.com/stealthrocket/dispatch-sdk-protobuf.git#branch=${{ env.GITHUB_BASE_REF || 'main' }}

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
    - uses: bufbuild/buf-push-action@v1
      with:
        buf_token: ${{ secrets.BUF_TOKEN }}
        draft: ${{ github.ref_name != 'main' }}
